; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	D:\junior\vs\da\da\client.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	??_C@_03ILJCGOLJ@?6?$CFs?$AA@			; `string'
PUBLIC	??_C@_0BF@LHDCNBPF@connect?$CI?$CJ?$DPFailed?3?$CFd?6?$AA@ ; `string'
PUBLIC	??_C@_09PFCHIMEP@127?40?40?41?$AA@		; `string'
PUBLIC	??_C@_0P@IKIOBIKE@socket?$DPerror?$DP?6?$AA@	; `string'
PUBLIC	??_C@_0BG@OMLAAHLM@?C?$PM?A?n?L?W?$LN?S?W?V?$LD?u?J?$LM?$LL?$KP?J?$KH?$LA?$NM?6?$AA@ ; `string'
PUBLIC	__$ArrayPad$
PUBLIC	_main
EXTRN	__imp__closesocket@4:PROC
EXTRN	__imp__recv@16:PROC
EXTRN	__imp__WSAGetLastError@0:PROC
EXTRN	__imp__connect@12:PROC
EXTRN	__imp__inet_addr@4:PROC
EXTRN	__imp__htons@4:PROC
EXTRN	_memset:PROC
EXTRN	__imp__socket@12:PROC
EXTRN	__imp__printf:PROC
EXTRN	__imp__WSAStartup@8:PROC
EXTRN	___security_cookie:DWORD
EXTRN	@__security_check_cookie@4:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT ??_C@_03ILJCGOLJ@?6?$CFs?$AA@
; File d:\junior\vs\da\da\client.c
CONST	SEGMENT
??_C@_03ILJCGOLJ@?6?$CFs?$AA@ DB 0aH, '%s', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@LHDCNBPF@connect?$CI?$CJ?$DPFailed?3?$CFd?6?$AA@
CONST	SEGMENT
??_C@_0BF@LHDCNBPF@connect?$CI?$CJ?$DPFailed?3?$CFd?6?$AA@ DB 'connect()?'
	DB	'Failed:%d', 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_09PFCHIMEP@127?40?40?41?$AA@
CONST	SEGMENT
??_C@_09PFCHIMEP@127?40?40?41?$AA@ DB '127.0.0.1', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@IKIOBIKE@socket?$DPerror?$DP?6?$AA@
CONST	SEGMENT
??_C@_0P@IKIOBIKE@socket?$DPerror?$DP?6?$AA@ DB 'socket?error?', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@OMLAAHLM@?C?$PM?A?n?L?W?$LN?S?W?V?$LD?u?J?$LM?$LL?$KP?J?$KH?$LA?$NM?6?$AA@
CONST	SEGMENT
??_C@_0BG@OMLAAHLM@?C?$PM?A?n?L?W?$LN?S?W?V?$LD?u?J?$LM?$LL?$KP?J?$KH?$LA?$NM?6?$AA@ DB 0c3H
	DB	0fcH, 0c1H, 0eeH, 0ccH, 0d7H, 0bdH, 0d3H, 0d7H, 0d6H, 0b3H, 0f5H
	DB	0caH, 0bcH, 0bbH, 0afH, 0caH, 0a7H, 0b0H, 0dcH, 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _main
_TEXT	SEGMENT
_wsaData$ = -1492					; size = 400
_timebuffer$ = -1084					; size = 1025
_servaddr$ = -48					; size = 16
_in$ = -24						; size = 4
_connectionFd$ = -12					; size = 4
__$ArrayPad$ = -4					; size = 4
_main	PROC						; COMDAT
; Line 8
	push	ebp
	mov	ebp, esp
	sub	esp, 1688				; 00000698H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-1688]
	mov	ecx, 422				; 000001a6H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
; Line 14
	mov	esi, esp
	lea	eax, DWORD PTR _wsaData$[ebp]
	push	eax
	push	514					; 00000202H
	call	DWORD PTR __imp__WSAStartup@8
	cmp	esi, esp
	call	__RTC_CheckEsp
	test	eax, eax
	je	SHORT $LN5@main
; Line 15
	mov	esi, esp
	push	OFFSET ??_C@_0BG@OMLAAHLM@?C?$PM?A?n?L?W?$LN?S?W?V?$LD?u?J?$LM?$LL?$KP?J?$KH?$LA?$NM?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 16
	or	eax, -1
	jmp	$LN6@main
$LN5@main:
; Line 18
	mov	esi, esp
	push	0
	push	1
	push	2
	call	DWORD PTR __imp__socket@12
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _connectionFd$[ebp], eax
; Line 19
	cmp	DWORD PTR _connectionFd$[ebp], -1
	jne	SHORT $LN4@main
; Line 20
	mov	esi, esp
	push	OFFSET ??_C@_0P@IKIOBIKE@socket?$DPerror?$DP?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 21
	or	eax, -1
	jmp	$LN6@main
$LN4@main:
; Line 23
	push	16					; 00000010H
	push	0
	lea	eax, DWORD PTR _servaddr$[ebp]
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
; Line 24
	mov	eax, 2
	mov	WORD PTR _servaddr$[ebp], ax
; Line 25
	mov	esi, esp
	push	13					; 0000000dH
	call	DWORD PTR __imp__htons@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	WORD PTR _servaddr$[ebp+2], ax
; Line 26
	mov	esi, esp
	push	OFFSET ??_C@_09PFCHIMEP@127?40?40?41?$AA@
	call	DWORD PTR __imp__inet_addr@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _servaddr$[ebp+4], eax
; Line 27
	mov	esi, esp
	push	16					; 00000010H
	lea	eax, DWORD PTR _servaddr$[ebp]
	push	eax
	mov	ecx, DWORD PTR _connectionFd$[ebp]
	push	ecx
	call	DWORD PTR __imp__connect@12
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, -1
	jne	SHORT $LN2@main
; Line 28
	mov	esi, esp
	call	DWORD PTR __imp__WSAGetLastError@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	push	OFFSET ??_C@_0BF@LHDCNBPF@connect?$CI?$CJ?$DPFailed?3?$CFd?6?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 8
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 29
	xor	eax, eax
	jmp	SHORT $LN6@main
$LN2@main:
; Line 32
	mov	esi, esp
	push	0
	push	1024					; 00000400H
	lea	eax, DWORD PTR _timebuffer$[ebp]
	push	eax
	mov	ecx, DWORD PTR _connectionFd$[ebp]
	push	ecx
	call	DWORD PTR __imp__recv@16
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _in$[ebp], eax
	cmp	DWORD PTR _in$[ebp], 0
	jle	SHORT $LN1@main
; Line 33
	mov	eax, DWORD PTR _in$[ebp]
	mov	BYTE PTR _timebuffer$[ebp+eax], 0
; Line 34
	mov	esi, esp
	lea	eax, DWORD PTR _timebuffer$[ebp]
	push	eax
	push	OFFSET ??_C@_03ILJCGOLJ@?6?$CFs?$AA@
	call	DWORD PTR __imp__printf
	add	esp, 8
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 35
	jmp	SHORT $LN2@main
$LN1@main:
; Line 36
	mov	esi, esp
	mov	eax, DWORD PTR _connectionFd$[ebp]
	push	eax
	call	DWORD PTR __imp__closesocket@4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 37
	xor	eax, eax
$LN6@main:
; Line 38
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN12@main
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 1688				; 00000698H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN12@main:
	DD	3
	DD	$LN11@main
$LN11@main:
	DD	-48					; ffffffd0H
	DD	16					; 00000010H
	DD	$LN8@main
	DD	-1084					; fffffbc4H
	DD	1025					; 00000401H
	DD	$LN9@main
	DD	-1492					; fffffa2cH
	DD	400					; 00000190H
	DD	$LN10@main
$LN10@main:
	DB	119					; 00000077H
	DB	115					; 00000073H
	DB	97					; 00000061H
	DB	68					; 00000044H
	DB	97					; 00000061H
	DB	116					; 00000074H
	DB	97					; 00000061H
	DB	0
$LN9@main:
	DB	116					; 00000074H
	DB	105					; 00000069H
	DB	109					; 0000006dH
	DB	101					; 00000065H
	DB	98					; 00000062H
	DB	117					; 00000075H
	DB	102					; 00000066H
	DB	102					; 00000066H
	DB	101					; 00000065H
	DB	114					; 00000072H
	DB	0
$LN8@main:
	DB	115					; 00000073H
	DB	101					; 00000065H
	DB	114					; 00000072H
	DB	118					; 00000076H
	DB	97					; 00000061H
	DB	100					; 00000064H
	DB	100					; 00000064H
	DB	114					; 00000072H
	DB	0
_main	ENDP
_TEXT	ENDS
END
